language: java
jdk:
- openjdk7
- oraclejdk8
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: BhgAC5xQXElO4SSdBiEGAYZYctSQr9bE/+BUWMDaUetvLPkk88cA+v6uxqVs3/n120i5zlrQRFMIf0/arkg9WJ774ONSCiffVZ+YWYkqh9ulCUkO96vqg6rFzmBU/G6xpSHlokfEghVMxJFmv3l+70r2p1A78uZqoHGKDCQl/qPsBfyq2t7/0IfxMjVyfpoxDtc22uh/rycB9r8c2ssAcwoMcrx8kkhRcpYyXFJuh5ybXumGA5KRjeXUa+VkRxoXiI29iuCAKf2E8lK5YL9OPzEQ499nRvecYprPndBMIToZM+2XQC8HGCxslj5tzrX+g0PiCxAfOgSqnp1MFMEZpnPKokuTI/dZZwZlqnAGHin4jl8swQ6ezrkk8LyUMlRo4yoNJr6sZBL1M2YwlNpYuOwYunj+bOJ69noO0OLMMZGVMaAWjFedz/63ckNIKRMsdRvTvPaCjjX7G1CvsWASGCF7fifTgM5cKFgcTfakUKXoIgqh0mvtWATkKI2vaOMafG5S2GgWCuuykTtb5mt4que43oScnl/dLociKDS0NSf9q16JwjtWavG2vfZD5chdwc1iVzw4h7lx0ouWr5Usy8JiBbQrCiNRjn0kKLqEhQ0N6w+9miV7ks1DOPiDfGRAdmY4FZ/6dnVt/d0UcPjN2C5/EXZGFzH10mDNAhVFDlA=
  - secure: f7uC6vgi101XMewjvH2K4m7k1jK9m0yUT56T/AEogZWcP3FsJYt1uOjGq6dhGWWDYpLzNyoMhPZTaJCG6Gvf2Jh92tKEZasPIymbQ/GIYDyeFG8UAbPx30z/7z2eCfNszkKOHMS3FRgSJ4urazOSQgN6h+UfgcUuQUGq3P+iAUKHdKlcUGsCzZObjnT4Ti6wKQhvcI2jtxr+YEkwZmfkYQ4bWfaALv9es1Bq5W1RoRjD1zNOvZ87M9cWKsLQh+15eOHXv58A6tSe3eRZGheQkpZTD6aUQ6dS/poeMcW6bLjEBr+qcg1Rm/oIFAXvs+pduHcMI5aYQhgCrZZbI1ZY+6bSmcE7huaDdAB7WX4zhVEVv+GQKiW9+KINCsJteI9PZ1quLTZnAeC3KAGemfTPVlAtzs8miyiW+dvhWWDTy+cL9jtNKw7F6RtOG+oqnLsmQ/dT/roUb3WZOt9wCe/gHOUb1Eariom/UaadCXOBxs1BsADW3vYgKyuEHYAP6aDEs0hWk12ORE1fwbVgH5OYpkA/QEFOgOq6VrhrbJ41Qog724kpuu9/aDUCV9lO6pzgcLZD2+9U4RYl62899v/M/8GMsvM6C3avtXjQmNBxopgiI4XygCNIoO+3HpOjJXY29pYNUJAWsQJkzxPUQYF63OFS2DxvzMCr957THE18Z9o=
