language: java
jdk:
- openjdk7
- oraclejdk8
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: OrE0eJQl9wQfqtRUmFJw+6WnTcU04LZJJqc/sd/FwfCkR2nBUpNCUB3uzjt3zvjtRWXKstEnuEHJwVt1bKKX6HqbUyYMdAfLz5Uiojm1PrXaMbHyDDG8OoJumAlVLzvHThcooKUhn3ciSStir/hhGiCe9z3z5QIBpucmM49D7ZmWq278K8Hvt3uO0xpvKq79ZK40YUwgUH5Ar5geAhXhJJQgsdTGfa/GMEWqzBHrA5dX9skzn7G14vaZa/291Dzq/qP8SEOGLHEp/aGavAm+N5p6+TVXs+mbk19tZPjanOCelTW6Q2589ouG78FfcS8a0UA6sLn2nzQUpSy5Yom4vfYCyl0evDt4f3HI0oX5hSoa0baa/LqDtZYOezagPwtYRxAqj1EBESbfYppgw6POCPIzn/5YjfPX1D/WZEE5jQm2PSXR8ywPI2LdzpQNGJyjQiWtyn0w0T5yu+OkzvViZ+gygjaD65pKfKVzUqpWdiiI+4E6FGsi4DLvxhkAf5ycfJXxzwFFqR+uFtFJICRs88DzFB42mcy/eM6tuPCFnCaNtNi0klLliGMHHN1ub78X304wUactaUsZXJ/78CUoQJEo1RR6JWRAYZgJe2B5qMThECaJuVWbEwDnaW3qMK+4u0TlbwcLeswnYXJhkIu4XDXUIX6xr5aLEuSCnslXHV8=
  - secure: bwvQej+eCJ8cD7j+p8knIRd7Ue0V2sG3bd6CK1eN919AzlVmDuKuYbmxEsWEuSNIaSW0LNDqxWHNdCfpyVcANx6Sic2FXVmaH85Unys2KNJCUlJa+EsB7wwvo5oVDimFA3oKZvln4n9Fr+YFbIK9vjuQniOVxCSySk5lDeoWH6fE7i43J/yuqQl5C44VZjMbsx2XffVqINgbIe6/PZichE2Ccw1ypU9u+5RFCHT5m401JeR2AbjxUSUZb+v6VLdyuFynX6fSTbZJ/K/Up6L3ao9IkTQD9l4cmtq94e+UAjSilGyunqV8cvPHkNX3/9ENabCr+TELBzfI4utG5/tPYaxnpoD5DmYFlIUsogDMt0e4xQ3tKUtQHITjXxYuNibudTQ5m553T26BTRYorzKZ3s6zGQkj89ueFOfbx9ya3YU4zDfi+oJCKc/4uak/8g5HGFLLTlr2nnQ0d+aUBsbWNpPeGoPwbjfWPI6JuF3GXYhS5R6L8csIfVT9/daIJAG50vrt9JAj1O56mpy/ed0kHwyLjtmAmI0yG6UKIb08Fv7Z6SEoQqfRdsUobuUDnF+sIx+Hog0frge0h3FHD+oqMdpIvVz05ZyF5DgyfoIQqezbD2U7VXTTdj+IX6dGOknZLsWW+DDnHl0HfnhMlbe58IR68zBXz/lTAHjFA6CxRag=
